### ISSUE TITLE
Reload from `sammy.sbt` on each run?

### ISSUE THREAD

**Issue by mrvisser** [zainab-ali/sbt-sammy#1]
One thing that might be helpful for those running a live sbt console would be to continue to reload the updated `sammy.sbt` on each run.

I think I have caught wind of other projects that do live reload, but one doesn't come to mind right now.

Thoughts?

**Comment by zainab-ali** [comment]
Thanks for the suggestion!  It's a flaw in the current implementation.

Doing a live reload would involve changing the `policeWarnings` task into a command that could modify the sbt state.  This will require a bit of re-engineering, but shouldn't be overly difficult.  I'll experiment with the idea.

**Comment by mrvisser** [comment]
I've since found that it is `sbt-release` that does this:

It's mentions it in step 6. under release process: https://github.com/sbt/sbt-release#release-process

I didn't think they had a separate task for it, though.

**Comment by zainab-ali** [comment]
This file looks to be where it's at: https://github.com/sbt/sbt-release/blob/master/src/main/scala-sbt-1.0/Compat.scala

**Comment by zainab-ali** [comment]
This has been released in v0.1.2
